local builtin = require("telescope.builtin")
vim.keymap.set('n', '<leader>qf', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>qg', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>qb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>qh', builtin.help_tags, { desc = 'Telescope help tags' })
